### ISSUE TITLE
Failed to load a language-hyperlink package grammar

### ISSUE THREAD

**Issue by wizardcc** [atom/language-hyperlink#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [language-hyperlink](https://github.com/atom/language-hyperlink) package 0.16.3

### Stack Trace

Failed to load a language-hyperlink package grammar

```
At Arguments to CompositeDisposable.add must have a .dispose() method in C:\Users\dell\AppData\Local\atom\app-1.26.0\resources\app.asar\node_modules\language-hyperlink\grammars\hyperlink.json

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at /packages/set-syntax/lib/main.coffee:14:20
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/first-mate/lib/grammar-registry.js:80:26)
    at Grammar.module.exports.Grammar.activate (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/first-mate/lib/grammar.js:259:54)
    at grammarRegistry.readGrammar (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:617:53)
    at CSON.readFile (~/AppData/Local/atom/app-1.26.0/resources/app/src/grammar-registry.js:468:15)
    at parseContents (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/season/lib/cson.js:123:13)
    at ~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/season/lib/cson.js:230:26
    at ELECTRON_ASAR.js:497:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
  at /app.asar/node_modules/language-hyperlink/grammars/hyperlink.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
an-color-picker 1.0.2 
atom-beautify 0.29.11 
atom-django 0.3.2 
atom-live-server 1.2.5 
atom-lorempixel 0.1.0 
atom-python-run 0.5.1 
atom-shortcuts 0.0.2 
autocomplete-python 1.8.2 
browser-plus 0.0.75 
color-picker 2.1.1 
cursor-blink-interval 0.3.1 
dark-bint-syntax 0.8.9 
django-atom 0.2.4 
doge 0.1.3 
es6-javascript 1.0.0 
file-icons 1.7.17 
filecolor 0.3.2 
genesis-syntax 1.0.7 
genesis-ui 0.5.0 
gitlab 0.1.3-7 
goto-definition 1.1.18 
high-street-ui 1.3.0 
highlight-column 0.5.1 
jquery-snippets 11.0.0 
language-django 0.1.1 
language-sql-mysql 0.3.1 
lazy-light-syntax 0.1.1 
linter 1.11.16 
linter-flake8 1.13.4 
linter-python-pyflakes 0.1.0 
MagicPython 0.5.15 
minimap-find-and-replace 4.5.1 
one-dark-shade-ui 0.1.0 
one-dark-vivid-syntax 1.1.2 
polymorph-ui 1.8.8 
python-autopep8 0.1.3 
python-snippets 1.9.0 
python-tools 0.6.8 
script 3.8.2 
script-runner 1.8.4 
set-syntax 0.3.0 
slim-dark-ui 0.12.0 
terminal-plus 0.14.5 
tree-view-copy-relative-path 1.0.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Similar/related to https://github.com/atom/autocomplete-plus/issues/851 I think?  I'll tentatively close as a duplicate for now and if you remember what you were doing at the time of the error, feel free to let us know.

Also, I see set-syntax in the stack trace:

>     at /packages/set-syntax/lib/main.coffee:14:20

Not sure if it's related but it looks like you have set-syntax 0.3.0 installed, maybe update that package as well?
